# Ler um modelo registado

Neste notebook iremos utilizar o modelo que registámos no notebook anterior para fazer previsões.

In [9]:
import mlflow
import pandas as pd

## Definir a diretoria onde as experiências são guardadas

In [10]:
from pathlib import Path

uri = "../../mlruns"

Path(uri).mkdir(parents=True, exist_ok=True)

mlflow.set_tracking_uri(uri)

# Carregar o Modelo

In [11]:
# Fazer load da versão do modelo "logistic_regression" que registamos no notebook anterior
# Têm de mudar a versão de acordo com quantas versões registaram.

model_name = "logistic_reg"
model_version = "2"
f"models:/{model_name}/{model_version}"

'models:/logistic_reg/2'

In [12]:
model = mlflow.pyfunc.load_model(f"models:/{model_name}/{model_version}")
model

mlflow.pyfunc.loaded_model:
  artifact_path: logistic_reg
  flavor: mlflow.sklearn
  run_id: 5f4bde44a49f4c158b22b5eefb04e08b

## Vamos utilizar o modelo lido para fazer previsões

In [13]:
data_path = '../../data/diabetes_test.csv'
df = pd.read_csv(data_path)

In [14]:
input_data = df.loc[df.Outcome == 1].sample(10)
input_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
11,0,138,60,35,167,34.6,0.534,21,1
98,7,129,68,49,125,38.5,0.439,43,1
53,0,140,65,26,130,42.6,0.431,24,1
81,7,181,84,21,192,35.9,0.586,51,1
41,0,138,0,0,0,36.3,0.933,25,1
78,5,85,74,22,0,29.0,1.224,32,1
102,8,196,76,29,280,37.5,0.605,57,1
17,3,163,70,18,105,31.6,0.268,28,1
63,3,158,70,30,328,35.5,0.344,35,1
13,10,161,68,23,132,25.5,0.326,47,1

In [15]:
input = input_data.drop("Outcome", axis=1)
input

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
11,0,138,60,35,167,34.6,0.534,21
98,7,129,68,49,125,38.5,0.439,43
53,0,140,65,26,130,42.6,0.431,24
81,7,181,84,21,192,35.9,0.586,51
41,0,138,0,0,0,36.3,0.933,25
78,5,85,74,22,0,29.0,1.224,32
102,8,196,76,29,280,37.5,0.605,57
17,3,163,70,18,105,31.6,0.268,28
63,3,158,70,30,328,35.5,0.344,35
13,10,161,68,23,132,25.5,0.326,47

In [16]:
model.predict(input)

array([0, 1, 1, 1, 1, 0, 1, 1, 1, 1])